version: '3.7'

services:
  bot:
    build: .
    depends_on:
      - db
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=cineman
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    env_file:
      - .env
